// The article: one claim, its own URL, and a declaration of what it rests on.
//
// This is the content type the site did not have, and its absence is the whole of the
// problem `.yidam/decisions/a-page-is-an-argument-not-an-inbox.yml` records. With only the
// page and the entry to choose between, every phase appended a section to whichever topic
// page was nearest; `/history` reached twenty-one of them and thirty-five minutes.
//
// **The registry is separate from the prose on purpose.** An `.astro` page cannot export
// metadata another module can read, so a reading room built over `import.meta.glob` would
// have to parse its own pages. Declaring here instead buys the thing that matters more: the
// `assertions` and `entries` a piece rests on are a *typed list*, so `articles.test.ts` can
// resolve every id against the feed and fail the build on one that does not — the same shape
// as the publication gate in `crates/publish`, one level up.
//
// The same test holds the registry and `src/pages/read/` to a one-to-one correspondence, so
// the two cannot drift.

import { assertions as feedAssertions, nodes } from './feeds'
import type { SectionKey } from './sections'

export interface Article {
  /** The URL is `/read/<slug>`, and the file is `src/pages/read/<slug>.astro`. */
  slug: string
  title: string
  /** One sentence, shown under the title and in the reading room. */
  dek: string
  section: SectionKey
  /**
   * The years the piece is about, for ordering within a section. A piece about a standing
   * condition rather than a span takes the year of the record it reads.
   */
  era: [number, number]
  /** Assertion ids from `series.json`. Every one is checked to resolve. */
  assertions: string[]
  /** Corpus node ids from `graph.json`, as `class/name.yml`. Every one is checked. */
  entries: string[]
}

/**
 * Every article, grouped by the section that links to it.
 *
 * Order within a section is by `era`, computed rather than declared, so adding a piece never
 * means renumbering its neighbours — which is exactly the maintenance the old page-appending
 * habit avoided by never ordering anything at all.
 */
export const ARTICLES: Article[] = [
  // ── Ground ──────────────────────────────────────────────────────────────
  {
    slug: 'what-the-ground-is',
    title: 'What the ground is',
    dek: 'The county was nine-tenths farmland in 1910 and is seven-tenths now; the missing third is built ground and woodland. And one spring in seventeen, a fifth of the cropland went unplanted.',
    section: 'ground',
    era: [2008, 2024],
    assertions: [
      'what-the-farmland-became',
      'the-spring-the-county-was-not-planted',
      'half-a-file-can-be-differenced',
      'soybeans-never-lost-the-lead',
    ],
    entries: [
      'measure/allen-county-land-cover-2008-2024.yml',
      'measure/allen-county-farmland-1910-2022.yml',
      'question/when-the-farmland-went.yml',
    ],
  },
  {
    slug: 'a-hog-county',
    title: 'A hog county',
    dek: 'The hogs multiplied while the farms keeping them halved, which is one fact about animals and another about who is left to keep them.',
    section: 'ground',
    era: [2002, 2022],
    assertions: ['the-hogs-multiplied-as-the-keepers-halved'],
    entries: ['place/allen-county.yml'],
  },
  {
    slug: 'first-in-ohio-and-the-air-is-clean',
    title: 'First in Ohio, and the air is clean',
    dek: 'No county in Ohio reported releasing more toxic chemical in 2024, and no year on record had fewer unhealthy days. Both are true and neither explains the other.',
    section: 'ground',
    era: [1980, 2024],
    assertions: [
      'the-county-leads-ohio-in-what-it-releases',
      'a-fifth-of-the-fall-is-the-list-changing',
      'what-goes-to-the-air-fell-and-the-wells-did-not',
      'what-ended-was-the-bad-day',
    ],
    entries: [
      'measure/allen-county-toxic-releases-1987-2024.yml',
      'measure/allen-county-air-quality-1980-2024.yml',
      'site/lima-refinery.yml',
    ],
  },
  {
    slug: 'where-the-lines-moved',
    title: 'Where the lines moved',
    dek: 'Fifty-seven dated annexations, and a county that lost land it never lost.',
    section: 'ground',
    era: [1990, 2024],
    assertions: ['the-annexations-are-dated-now', 'the-county-lost-land-it-never-lost'],
    entries: [
      'place/lima.yml',
      'place/allen-county.yml',
    ],
  },
  {
    slug: 'what-crosses-the-water',
    title: 'What crosses the water',
    dek: 'Three hundred and sixty-four bridges, and a state that replaced its own while the county kept its.',
    section: 'ground',
    era: [1992, 2025],
    assertions: ['not-one-state-bridge-is-in-poor-condition', 'the-state-replaced-its-bridges'],
    entries: [
      'site/hay-road-bridge.yml',
      'office/allen-county-engineer.yml',
    ],
  },
  {
    slug: 'the-river-measured',
    title: 'The river, measured',
    dek: 'The city drinks from a river nobody gauges, and the gauge everyone cites is somewhere else.',
    section: 'ground',
    era: [1920, 2026],
    assertions: ['the-gauge-was-not-there', 'the-city-drinks-from-the-river-nobody-measures'],
    entries: [
      'natural-feature/ottawa-river.yml',
      'event/the-ottawa-river-flood-of-1959.yml',
      'question/where-the-auglaize-rises.yml',
    ],
  },
  {
    slug: 'when-the-villages-began',
    title: 'When the villages began',
    dek: 'The county’s villages have incorporation dates now, and the order they arrive in is not the order the histories tell.',
    section: 'ground',
    era: [1831, 1912],
    assertions: ['the-villages-have-birthdays-now'],
    entries: [
      'event/the-incorporation-of-delphos-1851.yml',
      'event/the-naming-and-incorporation-of-bluffton-1861.yml',
      'event/the-organization-of-cairo-1875.yml',
      'question/what-happened-to-the-village-of-fort-shawnee.yml',
    ],
  },
  {
    slug: 'counted-two-ways',
    title: 'Counted two ways',
    dek: 'A federal gazetteer and a county map service disagree about how many named things stand on this ground, and both are right.',
    section: 'ground',
    era: [2026, 2026],
    assertions: ['a-county-column-is-a-filing-decision'],
    entries: ['place/allen-county.yml'],
  },
  {
    slug: 'the-weather-the-farms-are-in',
    title: 'The weather the farms are in',
    dek: 'The winters warmed and the summers did not, and there are three more weeks between the frosts than there were.',
    section: 'ground',
    era: [1895, 2025],
    assertions: [
      'the-winters-warmed-and-the-summers-did-not',
      'the-frost-free-season-is-three-weeks-longer',
    ],
    entries: [
      'place/allen-county.yml',
      'question/when-the-farmland-went.yml',
    ],
  },

  // ── People ──────────────────────────────────────────────────────────────
  {
    slug: 'the-ordinary-half',
    title: 'The ordinary half',
    dek: 'The county dies young, and cancer is not why. It kills at Ohio’s rate, falling — except among men, where it does not.',
    section: 'people',
    era: [2018, 2023],
    assertions: [
      'cancer-is-the-ordinary-half',
      'the-cancer-burden-is-a-mens-burden',
      'a-county-rank-comes-with-an-interval',
      'cancer-is-not-where-the-racial-gap-lives',
    ],
    entries: [
      'measure/allen-county-cancer-2018-2023.yml',
      'measure/allen-county-heart-disease-and-stroke-1999-2024.yml',
      'measure/allen-county-early-deaths-by-cause-2020-2022.yml',
    ],
  },
  {
    slug: 'fifth-worst-for-hearts',
    title: 'Fifth worst for hearts',
    dek: 'The county’s heart disease rate climbed while Ohio’s fell, and the gains that stopped in 2010 stopped only for people under 65.',
    section: 'people',
    era: [1999, 2024],
    assertions: [
      'fifth-worst-in-ohio-for-heart-disease',
      'the-improvement-stopped-at-working-age',
      'middling-on-hearts-worst-fifth-on-strokes',
    ],
    entries: ['place/allen-county.yml'],
  },
  {
    slug: 'the-schools-that-are-not-districts',
    title: 'The schools that are not districts',
    dek: 'Ten private schools and two community schools account for a third of the county’s missing children, in a survey whose roster cannot be differenced.',
    section: 'people',
    era: [2013, 2022],
    assertions: ['four-catholic-schools-hold-four-fifths', 'the-private-school-fall-is-in-the-file'],
    entries: ['place/allen-county.yml', 'place/lima.yml'],
  },
  {
    slug: 'lima-before-the-series-begins',
    title: 'Lima before the series begins',
    dek: 'The city grew fivefold after the oil, and the county outside it had three peaks thirty years apart.',
    section: 'people',
    era: [1880, 1970],
    assertions: [
      'lima-grew-fivefold-after-the-oil',
      'three-peaks-thirty-years-apart',
      'every-township-grew',
    ],
    entries: [
      'place/lima.yml',
      'period/lima-oil-boom.yml',
      'question/pre-1970-population-series.yml',
    ],
  },
  {
    slug: 'the-county-in-1920',
    title: 'The county in 1920',
    dek: 'The census counted what the county history had estimated, the migration arrived in the forties, and in 2000 the category itself split.',
    section: 'people',
    era: [1920, 2020],
    assertions: [
      'the-census-counted-what-the-history-estimated',
      'the-migration-arrived-in-the-forties',
      'the-category-split-in-2000',
    ],
    entries: [
      'place/allen-county.yml',
      'place/lima.yml',
    ],
  },
  {
    slug: 'who-is-not-in-a-house-at-all',
    title: 'Who is not in a house at all',
    dek: 'Three thousand people here live outside a household, and one census block was drawn along a prison fence.',
    section: 'people',
    era: [2020, 2020],
    assertions: [
      'three-thousand-people-live-outside-households',
      'the-census-drew-the-block-on-the-fence',
    ],
    entries: [
      'site/allen-correctional-institution.yml',
      'site/oakwood-correctional-facility.yml',
      'question/who-lives-in-the-county-without-housing.yml',
    ],
  },
  {
    slug: 'how-many-children',
    title: 'How many children',
    dek: 'The county has fewer children than it had, and through the 2010s they went missing faster than the classrooms did.',
    section: 'people',
    era: [2010, 2024],
    assertions: [
      'the-children-went-missing-faster-than-the-classrooms',
      'the-under-fives-are-the-births',
      'two-vintages-disagree-about-the-children',
    ],
    entries: [
      'measure/allen-county-children-2010-2024.yml',
      'measure/allen-county-natural-change-2021-2024.yml',
    ],
  },
  {
    slug: 'a-third-of-the-children',
    title: 'A third of the children',
    dek: 'The county has 6,910 fewer schoolchildren than in 1988, and its Black pupils are far less concentrated in Lima than they were.',
    section: 'people',
    era: [1988, 2024],
    assertions: [
      'a-third-of-the-schoolchildren-are-gone',
      'lima-holds-fewer-of-the-black-pupils',
      'the-share-that-held-because-both-halves-emptied',
    ],
    entries: [
      'measure/allen-county-school-enrolment-1988-2024.yml',
      'measure/allen-county-school-enrolment-by-race-1988-2024.yml',
    ],
  },
  {
    slug: 'one-renter-in-four',
    title: 'One renter in four',
    dek: 'Two thousand two hundred and fifty-one homes here have a federal subsidy on the rent, and eighty-six per cent of them are in Lima.',
    section: 'people',
    era: [2005, 2025],
    assertions: [
      'one-renter-household-in-six',
      'more-subsidized-housing-than-the-five-around-it',
      'the-same-homes-hold-fewer-people',
    ],
    entries: [
      'measure/allen-county-subsidized-housing-2005-2025.yml',
      'organization/allen-metropolitan-housing-authority.yml',
    ],
  },
  {
    slug: 'what-the-rent-takes',
    title: 'What the rent takes',
    dek: 'A renter here is two and a half times as likely as an owner to be paying more than they can afford, and almost the whole of it sits in the lowest income band.',
    section: 'people',
    era: [2006, 2022],
    assertions: [
      'renters-carry-what-owners-do-not',
      'the-burden-is-all-at-the-bottom',
      'a-black-renter-pays-more-of-less',
      'the-county-moved-and-the-country-did-not',
      'thirty-nine-homes-for-a-hundred-households',
    ],
    entries: [
      'measure/allen-county-housing-cost-burden-2006-2022.yml',
      'question/why-hud-and-the-survey-count-different-assisted-renters.yml',
    ],
  },
  {
    slug: 'seven-hundred-and-sixty',
    title: 'Seven hundred and sixty',
    dek: 'Fifty years of fatal crashes on this county\u2019s roads: a third fewer than there were, a year that stands outside the record, and a share with drink in it that has never moved.',
    section: 'people',
    era: [1975, 2024],
    assertions: [
      'seven-hundred-and-sixty-on-the-roads',
      'the-roads-followed-ohio-not-the-country',
      'the-worst-road-year-since-1978',
      'the-drink-share-never-moved',
      'the-crossings-stopped-killing-people',
    ],
    entries: [
      'measure/allen-county-road-deaths-1975-2024.yml',
      'measure/allen-county-rail-crossing-deaths-1980-2005.yml',
    ],
  },
  {
    slug: 'one-in-fifteen',
    title: 'One in fifteen',
    dek: 'An eviction case is filed against about one Allen County renter household in fifteen every year, and the number has not moved in seventeen years.',
    section: 'people',
    era: [2002, 2018],
    assertions: [
      'one-renter-household-in-fifteen-is-sued',
      'the-eviction-count-does-not-move',
      'busy-eviction-years-with-no-direction',
      'below-the-state-and-high-on-its-list',
      'a-filing-is-not-a-household',
    ],
    entries: [
      'measure/allen-county-evictions-2001-2018.yml',
      'measure/allen-county-housing-cost-burden-2006-2022.yml',
    ],
  },
  {
    slug: 'the-work-that-replaced-the-work',
    title: 'The work that replaced the work',
    dek: "Allen County's factories gave way to its hospitals and nursing homes, and the work that replaced them injures the people who do it about twice as often.",
    section: 'work',
    era: [2016, 2024],
    assertions: [
      'the-most-dangerous-work-here-is-care',
      'the-refinery-is-safer-than-the-nursing-home',
      'five-thousand-seven-hundred-recordable-injuries',
      'the-pandemic-is-in-the-injury-logs',
      'the-fall-is-real-and-the-trend-is-not',
      'three-workplace-deaths-and-that-is-ordinary',
      'a-plant-headcount-arrived-in-a-safety-filing',
      'one-workplace-in-ten-owes-a-safety-filing',
    ],
    entries: [
      'measure/allen-county-workplace-injuries-2016-2024.yml',
      'measure/allen-county-health-care-employment-2010-2022.yml',
      'site/lima-refinery.yml',
      'site/ford-lima-engine-plant.yml',
    ],
  },
  {
    slug: 'five-stars',
    title: 'Five stars',
    dek: "Twelve nursing homes hold 712.5 Allen County residents on any given night. CMS rates them well, and the rating was never asked what happens to the people who do the lifting.",
    section: 'people',
    era: [2011, 2026],
    assertions: [
      'twelve-homes-and-eight-hundred-and-eleven-beds',
      'two-thirds-of-the-beds-are-run-from-elsewhere',
      'better-rated-and-no-better-staffed',
      'two-hundred-and-eighty-seven-deficiencies',
      'a-five-star-home-is-the-most-dangerous-workplace',
      'the-homes-are-a-seventh-smaller-than-in-2013',
      'medicaid-pays-for-three-days-in-five',
    ],
    entries: [
      'measure/allen-county-nursing-homes-2026.yml',
      'measure/allen-county-nursing-home-days-2011-2023.yml',
      'measure/allen-county-group-quarters-2020.yml',
    ],
  },
  {
    slug: 'one-name-on-the-ballot',
    title: 'One name on the ballot',
    dek: "Allen County is its own seat in the Ohio House, and three times in eight elections nobody has run for it. A fifth of the county's voters leave the line blank when that happens.",
    section: 'government',
    era: [2000, 2020],
    assertions: [
      'the-county-is-its-own-house-district',
      'four-contests-with-one-name-on-the-ballot',
      'a-fifth-will-not-mark-an-unopposed-line',
      'one-seat-one-man-four-years-apart',
      'the-fourth-district-for-twenty-years',
      'one-name-on-this-ballot-for-twenty-years',
      'sherrod-brown-came-closest',
    ],
    entries: [
      'measure/allen-county-in-the-general-assembly-2000-2020.yml',
      'measure/allen-county-in-congress-2000-2020.yml',
      'measure/allen-county-governor-vote-2002-2018.yml',
    ],
  },
  {
    slug: 'what-comes-to-the-courthouse',
    title: 'What comes to the courthouse',
    dek: "Allen County's serious court shrank by more than a third in eleven years while its everyday court grew, foreclosures collapsed, and eviction filings did not move at all.",
    section: 'government',
    era: [2007, 2017],
    assertions: [
      'the-serious-court-shrank-and-the-everyday-one-grew',
      'crime-is-the-part-that-did-not-move',
      'juvenile-filings-fell-by-two-fifths',
      'seven-judges-hear-all-of-it',
      'one-collapsed-and-the-other-did-not-move',
      'three-renters-for-every-owner',
      'the-same-numbers-from-two-covers',
    ],
    entries: [
      'measure/allen-county-court-caseloads-2007-2017.yml',
      'measure/allen-county-foreclosures-and-evictions-2007-2017.yml',
      'measure/allen-county-evictions-2001-2018.yml',
    ],
  },
  {
    slug: 'the-adults-in-the-building',
    title: 'The adults in the building',
    dek: "Allen County's schools have a third fewer children than in 1992 and more of every kind of adult per child than they had \u2014 except the one who ran the library.",
    section: 'people',
    era: [1986, 2024],
    assertions: [
      'the-class-got-smaller-as-the-county-emptied',
      'every-adult-but-the-librarian',
      'eleven-districts-with-no-librarian',
      'the-administrators-that-did-not-leave',
      'one-aide-for-every-hundred-children',
      'the-psychologists-belong-to-the-service-center',
      'eight-buildings-and-seven-were-limas',
      'two-answers-that-arrive-at-the-same-building',
    ],
    entries: [
      'measure/allen-county-school-staffing-1992-2024.yml',
      'measure/allen-county-school-buildings-1986-2024.yml',
      'measure/allen-county-school-enrolment-1988-2024.yml',
    ],
  },
  {
    slug: 'more-children-and-fewer-patients',
    title: 'More children and fewer patients',
    dek: "Allen County has more children per woman than Ohio in every year measured, its infant mortality halved and then stopped, and its five hospitals admit fifteen per cent fewer people than in 2011 while keeping them slightly longer.",
    section: 'people',
    era: [2000, 2023],
    assertions: [
      'more-children-per-woman-than-ohio',
      'below-replacement-eleven-years-after-ohio',
      'prematurity-fell-and-birthweight-did-not',
      'infant-mortality-halved-then-stopped',
      'twenty-twenty-one-is-the-worst-year',
      'the-overlap-says-it-is-the-denominator',
      'fewer-patients-about-as-long',
      'the-work-went-outpatient',
      'occupancy-did-not-move-because-the-beds-came-out',
      'bluffton-has-stopped-taking-inpatients',
      'the-long-term-hospital-emptied-too',
      'the-two-big-hospitals-fell-in-proportion',
    ],
    entries: [
      'measure/allen-county-birth-outcomes-2000-2021.yml',
      'measure/allen-county-hospital-activity-2011-2023.yml',
      'measure/allen-county-hospital-beds-2011-2023.yml',
    ],
  },
  {
    slug: 'what-the-county-finished',
    title: 'What the county finished',
    dek: "One Allen County adult in five holds a bachelor's degree where Ohio has three in ten, the whole of the difference sits at the top of the ladder, and the survey that measures it describes five different populations of the same county without saying so.",
    section: 'people',
    era: [2005, 2023],
    assertions: [
      'one-adult-in-five-holds-a-degree',
      'the-deficit-is-all-at-the-far-end',
      'one-township-above-the-national-rate',
      'the-county-gained-and-the-state-gained-faster',
      'the-same-adults-better-educated',
      'lima-did-not-move-at-either-end',
      'the-disability-rate-is-not-a-county-rate',
      'five-tables-five-populations',
      'subtracting-two-universes-counts-an-institution',
      'the-profile-names-the-institution',
      'two-instruments-eleven-per-cent-apart',
      'the-same-subtraction-finds-the-armed-forces',
      'the-working-age-sex-ratio-is-a-prison',
      'in-lima-the-ratio-crosses-over',
      'the-poverty-rate-is-over-ninety-seven-thousand',
      'a-history-of-conscription',
    ],
    entries: [
      'measure/allen-county-educational-attainment-2009-2023.yml',
      'measure/allen-county-institutional-population-2023.yml',
      'measure/allen-county-group-quarters-2020.yml',
      'measure/allen-county-income-and-poverty-2023.yml',
    ],
  },
  {
    slug: 'what-the-county-gives',
    title: 'What the county gives',
    dek: "Allen County's federal political giving is five times what it was in 1980 in real terms, its median contribution has fallen from $860 to $24, and a careless reading of the same file would put the total two and a half times too high.",
    section: 'government',
    era: [1980, 2024],
    assertions: [
      'what-the-county-gives',
      'five-times-the-real-giving',
      'the-1984-row-is-the-file',
      'the-median-gift-fell-a-hundredfold',
      'both-tails-grew-at-once',
      'no-factory-worker-in-thirty-three-years',
      'the-congressman-is-the-largest-recipient',
      'the-money-is-more-republican-than-the-vote',
      'half-the-money-has-no-party',
      'reading-the-archive-twice',
      'the-zip-rule-is-worth-a-factor-of-two',
      'twenty-postal-areas-touch-the-county',
      'the-join-closes-on-the-county',
      'land-is-the-wrong-weight-for-people',
      'three-towns-a-land-weight-misplaces',
    ],
    entries: [
      'measure/allen-county-federal-contributions-1980-2024.yml',
      'measure/allen-county-zip-codes-2020.yml',
      'measure/allen-county-presidential-vote-2000-2016.yml',
    ],
  },
  {
    slug: 'what-happens-in-the-building',
    title: 'What happens in the building',
    dek: 'Nearly one Black schoolchild in three was suspended out of school in Allen County in 2013–14, chronic absence has doubled since, and the seven school buildings Lima is said to have lost turn out to be a turnover of nineteen.',
    section: 'people',
    era: [1986, 2022],
    assertions: [
      'one-black-child-in-three-suspended',
      'the-county-suspends-more-of-everybody',
      'a-third-of-suspensions-a-seventh-of-the-roll',
      'suspension-halved-in-two-years',
      'ohio-stopped-suspending-and-this-county-did-not',
      'no-expulsion-figure-for-2013',
      'absenteeism-doubled',
      'half-the-black-children-absent',
      'better-on-absence-worse-on-suspension',
      'two-collections-disagree-about-the-children',
      'the-net-of-seven-is-a-turnover-of-nineteen',
      'ten-buildings-in-four-years',
      'named-for-people-named-for-ideas',
      'one-identifier-two-schools',
    ],
    entries: [
      'measure/allen-county-school-discipline-2011-2021.yml',
      'measure/allen-county-chronic-absenteeism-2013-2022.yml',
      'measure/allen-county-school-buildings-1986-2024.yml',
      'measure/allen-county-school-enrolment-by-race-1988-2024.yml',
    ],
  },
  {
    slug: 'nine-parts-beech',
    title: 'Nine parts beech',
    dek: "Allen County was ninety-one per cent beech forest and eight per cent swamp, not the other way round; nine miles of continental divide cross it without a hill; and its lowest point is a quarry pit deeper than the county is tall.",
    section: 'ground',
    era: [1820, 2026],
    assertions: [
      'three-hundred-and-thirty-seven-feet',
      'the-high-point-is-on-the-divide',
      'nine-miles-of-continental-divide',
      'a-divide-nine-miles-long-and-seventy-four-feet-tall',
      'two-thousand-three-hundred-acres-drain-to-the-gulf',
      'nine-parts-beech',
      'it-is-not-one-swamp-it-is-nineteen',
      'the-hydric-proxy-was-four-times-too-big',
      'the-proxy-got-the-order-and-not-the-places',
      'three-quarters-of-the-wet-ground-was-beech',
      'the-lowest-point-is-a-hole-somebody-dug',
      'the-hole-is-deeper-than-the-county',
    ],
    entries: [
      'measure/allen-county-elevation-2026.yml',
      'measure/allen-county-original-vegetation.yml',
      'natural-feature/great-black-swamp.yml',
    ],
  },
  {
    slug: 'the-money-that-does-not-come-from-work',
    title: 'The money that does not come from work',
    dek: "Income per person in Allen County is three quarters higher in real terms than in 1969 and a job here pays four per cent more. More than half the difference is government transfers, half of those are medical, and the federal award record does not contain them.",
    section: 'work',
    era: [1969, 2024],
    assertions: [
      'income-rose-and-earnings-barely-did',
      'twenty-years-to-get-back-to-1979',
      'a-job-here-pays-what-it-paid-in-1969',
      'half-the-growth-is-transfers',
      'a-quarter-of-the-income-is-a-transfer',
      'half-the-transfers-are-medical',
      'the-composition-inverted',
      'two-federal-accounts-of-one-county',
      'the-difference-is-medicare-and-medicaid',
      'ordinary-for-ohio-and-ohio-is-not-its-median',
      'the-gap-with-the-nation-is-in-the-growth-rate',
      'half-a-billion-in-earnings-goes-home-elsewhere',
    ],
    entries: [
      'measure/allen-county-personal-income-1969-2024.yml',
      'measure/allen-county-transfer-receipts-1969-2024.yml',
      'measure/federal-money-in-allen-county-2008-2025.yml',
    ],
  },
  {
    slug: 'the-peak-was-1979',
    title: 'The peak was 1979',
    dek: "A house in Allen County is worth less in real terms than it was fifty years ago \u2014 one of forty-four counties in America of which that is true, and eight of the forty-four are in Ohio. And seven census tracts in Lima have no house price at all.",
    section: 'people',
    era: [1975, 2025],
    assertions: [
      'a-house-worth-less-than-in-1975',
      'the-peak-was-1979',
      'the-floor-was-2014',
      'the-nation-gained-what-this-county-lost',
      'forty-four-counties-below-1975',
      'the-jobs-came-back-the-prices-did-not',
      'a-tax-base-at-half-the-market-pace',
      'seven-lima-tracts-with-no-price',
      'the-index-stops-where-the-lending-stops',
      'where-the-index-sees-lima',
    ],
    entries: [
      'measure/allen-county-house-prices-1975-2025.yml',
      'measure/allen-county-house-prices-by-tract-1986-2025.yml',
      'measure/allen-county-housing-stock-2023.yml',
    ],
  },
  {
    slug: 'two-addresses-for-one-dollar',
    title: 'Two addresses for one dollar',
    dek: "The United States spends $668 million a year in Allen County. Ninety-three per cent of it is cheques to individuals, and almost all of the rest is bought by the Department of Defense from companies with addresses somewhere else.",
    section: 'government',
    era: [2008, 2025],
    assertions: [
      'six-thousand-six-hundred-a-head',
      'four-social-security-programmes',
      'the-biggest-federal-grant-here-is-roads',
      'one-billion-and-one-hundred-and-fifty-five-million',
      'ninety-seven-per-cent-defence',
      'four-firms-and-one-is-from-here',
      'forty-two-tanks-for-saudi-arabia',
      'the-forge-and-the-refinery',
    ],
    entries: [
      'measure/federal-money-in-allen-county-2008-2025.yml',
      'measure/federal-contracts-in-allen-county-2008-2025.yml',
      'site/lima-army-tank-plant.yml',
    ],
  },
  {
    slug: 'fifty-four-square-feet',
    title: 'Fifty-four square feet',
    dek: "A federal court spent seven years on the state hospital north of Lima. Its first order was copied from Alabama; its findings, six years later, are the best record this county has of the largest institution ever built in it.",
    section: 'history',
    era: [1915, 2021],
    assertions: [
      'three-opinions-one-docket-one-judge',
      'a-remedy-copied-from-alabama',
      'a-thousand-two-hundred-and-ninety-five-to-four-hundred',
      'fifty-four-square-feet-against-an-ordered-eighty',
      'forty-four-point-eight-per-cent',
      'one-hundred-and-eighty-seven-opinions',
      'the-nineteen-seventies-peak-is-the-law',
      'litigated-in-other-peoples-counties',
    ],
    entries: [
      'event/davis-v-watkins.yml',
      'measure/lima-state-hospital-in-the-reports-1920-2021.yml',
      'site/lima-state-hospital.yml',
    ],
  },
  {
    slug: 'one-mile-in-six',
    title: 'One mile in six',
    dek: "Allen County has 2,225.6 miles of road and one federal file names the owner of 359.2 of them. The rest belong to nine municipalities, twelve townships and a county engineer, and no source says which.",
    section: 'ground',
    era: [2010, 2024],
    assertions: [
      'two-thousand-two-hundred-and-twenty-five-miles',
      'one-mile-in-six-has-an-owner',
      'a-hundredth-of-the-road-and-a-third-of-the-traffic',
      'every-ownership-change-is-a-corporation-line',
      'a-thirtieth-of-the-ground-and-an-eighth-of-the-road',
      'three-times-the-road-per-head-outside-lima',
      'one-interstate-drawn-twice',
      'the-map-stopped-before-the-county-did',
    ],
    entries: [
      'measure/allen-county-roads-2010-2024.yml',
      'measure/allen-county-federal-aid-highways-2018.yml',
      'measure/allen-county-bridges-2025.yml',
    ],
  },
  {
    slug: 'two-working-faces',
    title: 'Two working faces',
    dek: 'Six mines have been registered in Allen County and two are still worked, by about thirty people between them — and one of them is the company that sold Ford the ground its engine plant stands on.',
    section: 'ground',
    era: [1944, 2025],
    assertions: [
      'six-registrations-two-working-faces',
      'a-quarry-inside-a-village',
      'the-quarry-and-the-engine-plant',
      'thirty-four-injuries-and-no-death',
      'the-registers-oldest-date-is-not-a-date',
    ],
    entries: [
      'measure/allen-county-quarries-2000-2025.yml',
      'site/national-lime-and-stone-lima-quarry.yml',
      'site/ford-lima-engine-plant.yml',
    ],
  },
  {
    slug: 'the-wells-that-are-still-there',
    title: 'The wells that are still there',
    dek: 'The 1885 oil strike is the best-dated event in this county\u2019s history. Nobody had counted what it left behind: 4,849 holes, and no paper closing most of them.',
    section: 'ground',
    era: [1885, 2026],
    assertions: [
      'two-thousand-eight-hundred-wells-with-no-plugging-on-file',
      'a-hundred-and-eight-orphan-wells',
      'the-oil-field-is-a-shape-east-of-the-city',
      'one-formation-at-one-depth',
      'the-register-begins-after-the-field-does',
    ],
    entries: [
      'measure/allen-county-oil-and-gas-wells-2026.yml',
      'period/lima-oil-boom.yml',
    ],
  },
  {
    slug: 'prime-if-drained',
    title: 'Prime if drained',
    dek: 'Three quarters of this county drains badly, and five acres in six of its prime farmland are prime only because somebody took the water off.',
    section: 'ground',
    era: [1831, 2025],
    assertions: [
      'three-quarters-of-the-county-drains-badly',
      'prime-only-because-it-was-drained',
      'the-black-swamp-here-is-clay',
      'two-files-a-hundred-and-thirty-times-apart',
      'the-wet-ground-runs-north-and-west',
      'the-county-seat-is-on-the-driest-ground',
    ],
    entries: [
      'measure/allen-county-soils-2026.yml',
      'natural-feature/great-black-swamp.yml',
    ],
  },
  {
    slug: 'the-only-legible-district',
    title: 'The only legible district',
    dek: 'Ten years of graduation rates and test scores for twelve districts \u2014 and a disclosure rule that makes exactly one of them readable.',
    section: 'people',
    era: [2009, 2019],
    assertions: [
      'lima-reads-at-forty-two-per-cent',
      'twelve-districts-fell-in-the-same-two-years',
      'the-county-passed-the-state-without-improving',
      'the-only-district-published-as-a-number',
      'limas-graduation-rate-has-not-moved',
      'the-county-graduation-rate-fell-and-the-states-rose',
      'no-racial-gap-in-limas-graduation-rate',
    ],
    entries: [
      'measure/allen-county-graduation-rates-2010-2019.yml',
      'measure/allen-county-test-proficiency-2009-2020.yml',
    ],
  },
  {
    slug: 'the-roll-and-the-room',
    title: 'The roll and the room',
    dek: 'Eleven elections of machinery rather than result: what a turnout rate is divided by, and who is left to run the count.',
    section: 'government',
    era: [2004, 2024],
    assertions: [
      'two-thousand-and-twenty-was-an-ordinary-year',
      'the-county-used-to-out-vote-ohio',
      'sixty-one-thousand-names-off-a-sixty-six-thousand-roll',
      'election-day-stopped-being-the-day',
      'two-hundred-and-fifty-two-people-run-it',
      'a-quarter-of-the-provisional-ballots-were-rejected',
    ],
    entries: [
      'measure/allen-county-turnout-2004-2024.yml',
      'measure/allen-county-voter-roll-removals-2006-2022.yml',
      'measure/allen-county-polling-places-2004-2024.yml',
    ],
  },
  {
    slug: 'fewer-doors',
    title: 'Fewer doors',
    dek: 'A fifth of this county\u2019s workplaces are gone and almost all of its jobs are not. What went was the shops with under ten people in them.',
    section: 'work',
    era: [1986, 2023],
    assertions: [
      'a-fifth-of-the-workplaces-are-gone',
      'the-small-workplaces-are-what-went',
      'pay-that-has-not-moved-in-thirty-seven-years',
      'retail-lost-more-than-manufacturing',
      'the-two-largest-sectors-are-level-again',
    ],
    entries: [
      'measure/allen-county-private-employers-1986-2023.yml',
      'measure/allen-county-manufacturing-employment-1986-2022.yml',
    ],
  },
  {
    slug: 'buying-and-borrowing',
    title: 'Buying, and borrowing against what you own',
    dek: 'Seven years of mortgage applications, and a denial gap that income does not account for.',
    section: 'people',
    era: [2018, 2024],
    assertions: [
      'borrowing-against-a-house-in-lima',
      'the-denial-gap-is-seven-years-old',
      'the-lending-gap-is-not-composition',
      'the-denial-gap-that-does-not-resolve',
    ],
    entries: [
      'question/why-allen-countys-lending-outcomes-differ.yml',
      'place/lima.yml',
    ],
  },
  {
    slug: 'the-overdose-epidemic-ending',
    title: 'The overdose epidemic, ending',
    dek: 'Overdose deaths fell by two thirds from their peak, and the fall is steeper here than in the state.',
    section: 'people',
    era: [2017, 2025],
    assertions: ['overdose-deaths-fell-by-two-thirds'],
    entries: ['place/allen-county.yml'],
  },
  {
    slug: 'where-a-districts-money-comes-from',
    title: 'Where a district’s money comes from',
    dek: 'The district that spends the most per pupil raises the least of it locally.',
    section: 'people',
    era: [2023, 2023],
    assertions: ['lima-schools-spend-most-and-raise-least'],
    entries: ['place/lima.yml'],
  },
  {
    slug: 'who-governs-the-districts',
    title: 'Who governs the districts',
    dek: 'Twelve school boards, elected on a ballot most of the county never sees.',
    section: 'people',
    era: [2026, 2026],
    assertions: [],
    entries: ['question/why-one-child-in-five-is-not-in-these-districts.yml'],
  },
  {
    slug: 'after-the-twelfth-grade',
    title: 'After the twelfth grade',
    dek: 'The county lost a third of its college students, and its second-largest field of study is not a local job.',
    section: 'people',
    era: [2010, 2024],
    assertions: [
      'the-county-lost-a-third-of-its-college-students',
      'the-second-largest-field-of-study-is-not-a-local-one',
      'in-state-tuition-here-runs-eightfold',
    ],
    entries: [
      'organization/james-a-rhodes-state-college.yml',
      'organization/bluffton-university.yml',
      'organization/ohio-state-university-at-lima.yml',
      'organization/university-of-northwestern-ohio.yml',
    ],
  },

  // ── Work ────────────────────────────────────────────────────────────────
  {
    slug: 'nobodys-payroll',
    title: 'Nobody’s payroll',
    dek: 'Three federal programmes count this county’s jobs and differ by fourteen thousand. Most of the difference is people working for themselves — nearly one job in five, the highest in fifty-four years.',
    section: 'work',
    era: [1969, 2022],
    assertions: [
      'one-job-in-five-is-nobodys-payroll',
      'every-job-lost-since-2001-is-a-payroll-job',
      'the-farm-proprietors-halved',
    ],
    entries: [
      'measure/allen-county-proprietors-1969-2022.yml',
      'measure/allen-county-total-employment-1969-2022.yml',
      'measure/allen-county-occupations-2014-2024.yml',
    ],
  },
  {
    slug: 'what-the-work-is',
    title: 'What the work is',
    dek: 'Production is still the county’s largest occupation and more concentrated than a decade ago, and the clerical collapse underneath is smaller than it first reads.',
    section: 'work',
    era: [2014, 2024],
    assertions: [
      'the-county-kept-making-things',
      'the-fingerprint-names-the-landmarks',
      'the-clerks-went-and-the-warehouse-did-not-arrive',
    ],
    entries: ['place/allen-county.yml', 'site/lima-refinery.yml'],
  },
  {
    slug: 'the-rate-caught-up-with-ohio',
    title: 'The rate caught up with Ohio',
    dek: 'Twenty-four years above the state’s unemployment rate, and then a convergence made mostly of people leaving the labour force.',
    section: 'work',
    era: [1990, 2026],
    assertions: ['the-rate-converged-and-the-workforce-did-not'],
    entries: ['place/allen-county.yml'],
  },
  {
    slug: 'the-factories-left-lima',
    title: 'The factories left Lima',
    dek: 'They did not leave the county. Lima’s share of the factory workforce fell for forty years while the county’s held.',
    section: 'work',
    era: [1929, 1967],
    assertions: ['the-factories-left-lima-and-not-the-county'],
    entries: [
      'place/lima.yml',
      'period/deindustrialization.yml',
    ],
  },

  // ── Government ──────────────────────────────────────────────────────────
  {
    slug: 'what-a-mill-is-worth',
    title: 'What a mill is worth',
    dek: 'One mill on this county raises $2,451,332, no two of its thirty-six taxing districts charge the same, and one of them stopped being a village.',
    section: 'government',
    era: [2012, 2025],
    assertions: [
      'what-a-mill-is-worth-here',
      'the-column-changed-and-the-rate-did-not',
      'the-school-district-is-the-tax-bill',
      'the-village-stopped-levying-and-the-township-took-it',
    ],
    entries: [
      'measure/allen-county-property-tax-rates-2012-2025.yml',
      'measure/allen-county-assessed-valuation-2010-2023.yml',
      'question/what-happened-to-the-village-of-fort-shawnee.yml',
    ],
  },
  {
    slug: 'the-democratic-column',
    title: 'The Democratic column',
    dek: 'Five elections added to the modern run, and a third of one column gone in eight years while the other grew.',
    section: 'government',
    era: [2000, 2020],
    assertions: ['the-democratic-column-lost-a-third-of-itself'],
    entries: ['place/allen-county.yml'],
  },
  {
    slug: 'the-government-below-the-county',
    title: 'The government below the county',
    dek: 'Thirteen townships, nine villages and a city — and in two of the villages, appointment is how the government gets filled.',
    section: 'government',
    era: [2026, 2026],
    assertions: [
      'the-townships-are-named',
      'appointment-is-a-form-of-local-government',
      'two-villages-cannot-fill-their-governments',
      'lima-elects-by-ward-and-fills-its-seats',
    ],
    entries: [
      'jurisdiction/allen-county-government.yml',
      'question/why-allen-countys-villages-are-staffed-by-appointment.yml',
    ],
  },
  {
    slug: 'who-polices-the-county',
    title: 'Who polices the county',
    dek: 'A step in the reported numbers that is not a crime wave, and what changed underneath it.',
    section: 'government',
    era: [1985, 2024],
    assertions: ['a-step-that-is-not-a-crime-wave'],
    entries: [
      'office/allen-county-sheriff.yml',
      'measure/allen-county-sheriff-offenses-2015-2024.yml',
    ],
  },
  {
    slug: 'the-mayors-and-where-the-office-went',
    title: 'The mayors, and where the office went',
    dek: 'Three books, four slots, a year with nobody in it, and a line of Lima mayors that reaches 1922.',
    section: 'government',
    era: [1842, 1922],
    assertions: ['the-mayoral-line-reaches-1922', 'the-1906-list-lost-a-year'],
    entries: [
      'office/mayor-of-lima.yml',
      'event/lima-adopts-commission-government-1922.yml',
    ],
  },
  {
    slug: 'twelve-boards-nine-ballots',
    title: 'Twelve boards, nine ballots',
    dek: 'Twelve governing boards hold ground in this county and nine of them are elected — on ballots that do not line up.',
    section: 'government',
    era: [2026, 2026],
    assertions: ['twelve-boards-and-nine-ballots'],
    entries: ['jurisdiction/allen-county-government.yml'],
  },
  {
    slug: 'what-the-bar-register-knows',
    title: 'What the bar register knows',
    dek: 'It dates every admission to the day and cannot say where anybody practised — and it dots a ninety-nine-year hole.',
    section: 'government',
    era: [1850, 2026],
    assertions: [
      'the-register-dates-them-but-cannot-place-them',
      'the-ninety-nine-year-hole-is-dotted',
    ],
    entries: ['place/allen-county.yml'],
  },
  {
    slug: 'three-cents-in-the-dollar',
    title: 'Three cents in the dollar',
    dek: 'The county’s public library raises three per cent of its money locally, and the rest arrives from Columbus.',
    section: 'government',
    era: [2024, 2024],
    assertions: ['three-per-cent-of-the-library-money-is-local'],
    entries: [
      'organization/lima-public-library.yml',
      'organization/bluffton-public-library.yml',
      'organization/delphos-public-library.yml',
    ],
  },
  {
    slug: 'three-rosters-one-checkable',
    title: 'Three rosters, one checkable',
    dek: 'A 1906 book prints a line of holders for every office, and only one of its three rosters can be tested against anything.',
    section: 'government',
    era: [1831, 1906],
    assertions: [
      'a-line-of-holders-for-every-office',
      'three-rosters-and-only-one-can-be-checked',
      'the-board-is-printed-as-a-shift-register',
    ],
    entries: [
      'office/allen-county-board-of-commissioners.yml',
      'office/allen-county-sheriff.yml',
    ],
  },
  {
    slug: 'the-one-democrat',
    title: 'The one Democrat',
    dek: 'In 2006 the county voted for a Democrat for governor — and for a Republican in every other race on the same ballot.',
    section: 'government',
    era: [2002, 2020],
    assertions: [
      'the-one-election-it-gave-a-democrat',
      'one-democrat-carried-it-and-seven-did-not',
      'the-presidential-premium-is-twenty-three-points',
    ],
    entries: [
      'measure/allen-county-governor-vote-2002-2018.yml',
      'measure/allen-county-ballot-2006.yml',
    ],
  },
  {
    slug: 'the-county-changed-sides',
    title: 'The county changed sides',
    dek: 'It was Democratic ground for thirty years, and it did not turn with 1896 — it turned before.',
    section: 'government',
    era: [1856, 1908],
    assertions: ['the-county-changed-sides', 'the-county-did-not-turn-with-1896'],
    entries: ['place/allen-county.yml'],
  },

  // ── History ─────────────────────────────────────────────────────────────
  {
    slug: 'the-fort-across-the-line',
    title: 'The fort across the line',
    dek: 'The county’s first settlement, first post office and the fort a township is named for all stand nine hundred and ninety feet outside it.',
    section: 'history',
    era: [1812, 1848],
    assertions: ['the-county-is-settled-from-outside-itself'],
    entries: [
      'site/fort-amanda.yml',
      'event/the-building-of-fort-amanda-1812.yml',
      'event/settlers-occupy-fort-amanda-1817.yml',
      'place/amanda-township.yml',
    ],
  },
  {
    slug: 'who-the-county-is-named-for',
    title: 'Who the county is named for',
    dek: 'The earliest printed account of Ohio’s counties says a colonel of the War of 1812, and cannot name him.',
    section: 'history',
    era: [1820, 1847],
    assertions: ['a-colonel-of-that-name-in-the-war-of-1812'],
    entries: [
      'question/namesake-of-allen-county.yml',
      'event/erection-of-allen-county.yml',
    ],
  },
  {
    slug: 'the-road-under-four-names',
    title: 'The road under four names',
    dek: 'A county history totals its own railroad columns to the unit, forecasts from them, and the forecast does not follow.',
    section: 'history',
    era: [1854, 2026],
    assertions: [
      'the-page-adds-up-and-the-forecast-does-not',
      'no-passenger-train-calls-in-this-county',
    ],
    entries: [
      'event/the-first-railroad-reaches-allen-county.yml',
      'site/lima-pennsylvania-railroad-depot.yml',
      'organization/ohio-electric-railway.yml',
    ],
  },
  {
    slug: 'one-person-in-ten',
    title: 'One person in ten',
    dek: 'The county put 1,920 men into the Civil War and its roster never added up its own dead.',
    section: 'history',
    era: [1861, 1885],
    assertions: [
      'one-person-in-ten-went-to-war',
      'the-roster-never-totalled-its-own-dead',
      'more-died-at-corinth-than-anywhere',
    ],
    entries: [
      'period/the-civil-war-in-allen-county.yml',
      'event/the-first-lima-company-1861.yml',
    ],
  },
  {
    slug: 'three-times-a-crowd-came-to-the-jail',
    title: 'Three times a crowd came to the jail',
    dek: 'Sixty-one years, three crowds, and an office that passed from father to son because of the last of them.',
    section: 'history',
    era: [1872, 1933],
    assertions: ['three-times-a-mob-came-to-the-jail', 'the-office-passed-from-father-to-son'],
    entries: [
      'event/allen-county-jail-raid-1933.yml',
      'event/the-mob-at-the-allen-county-jail-1916.yml',
      'event/the-execution-of-andrew-brentlinger-1872.yml',
      'office/allen-county-sheriff.yml',
    ],
  },
  {
    slug: 'two-counts-of-one-war',
    title: 'Two counts of one war',
    dek: 'The county counted its World War soldiers twice and got different answers, and the man its Legion post is named for is in only one of them.',
    section: 'history',
    era: [1917, 1921],
    assertions: ['the-two-war-lists-do-not-join'],
    entries: ['period/the-world-war-in-allen-county.yml'],
  },
  {
    slug: 'a-hundred-and-sixty-congregations',
    title: 'A hundred and sixty congregations',
    dek: 'Forty-nine religious bodies report 58,696 adherents here, and a survey a century earlier counted differently on purpose.',
    section: 'history',
    era: [1906, 2020],
    assertions: ['a-hundred-and-sixty-congregations'],
    entries: [
      'organization/market-street-presbyterian-church.yml',
      'organization/trinity-methodist-episcopal-church.yml',
      'question/when-limas-first-congregation-was-organized.yml',
    ],
  },
  {
    slug: 'ninety-nine-papers',
    title: 'Ninety-nine papers',
    dek: 'Ninety-nine newspapers have been printed in Allen County. One is digitized, and forty-three have no library reporting a copy.',
    section: 'history',
    era: [1843, 2026],
    assertions: ['ninety-nine-papers-and-one-of-them-online'],
    entries: [
      'organization/the-lima-news.yml',
      'organization/the-lima-argus.yml',
      'organization/the-lima-citizen.yml',
      'organization/der-lima-courier.yml',
    ],
  },
  {
    slug: 'two-tank-plants',
    title: 'Two tank plants',
    dek: 'Two tank installations, a year and a category apart — and the one that turned out to be the plant standing there now.',
    section: 'history',
    era: [1939, 1947],
    assertions: [
      'the-county-had-two-tank-installations',
      'the-war-turned-the-locomotive-works-books',
    ],
    entries: [
      'site/lima-army-tank-plant.yml',
      'organization/lima-locomotive-works.yml',
      'event/the-united-states-buys-the-tank-plant-ground-1951.yml',
      'event/the-army-builds-at-lima-1942.yml',
    ],
  },
  {
    slug: 'one-hundred-and-seventy-one',
    title: 'One hundred and seventy-one',
    dek: 'The third war is counted here by its dead: one Army casualty for every 429 people the county held.',
    section: 'history',
    era: [1941, 1946],
    assertions: ['the-third-war-is-counted-by-its-dead'],
    entries: ['period/the-second-world-war-in-allen-county.yml'],
  },
  {
    slug: 'what-a-tract-book-knows',
    title: 'What a tract book knows',
    dek: 'The county has abstracted its conveyances by piece of ground since the federal patents, and a conveyance is dated whether or not anybody reported it.',
    section: 'history',
    era: [1831, 2026],
    assertions: [],
    entries: ['office/allen-county-recorder.yml'],
  },
  {
    slug: 'twenty-nine-on-the-register',
    title: 'Twenty-nine on the register',
    dek: 'Sixteen of the county’s National Register properties were signed on one day in 1982, and nothing on the list made anything.',
    section: 'history',
    era: [1970, 2026],
    assertions: ['sixteen-of-twenty-nine-are-one-days-work'],
    entries: [
      'site/allen-county-courthouse.yml',
      'site/lima-memorial-hall.yml',
    ],
  },
  {
    slug: 'what-the-sky-did',
    title: 'What the sky did',
    dek: 'A thirty-fold rise in severe weather reports that is mostly categories arriving — and eighty-four cents in every disaster dollar is one pandemic.',
    section: 'history',
    era: [1950, 2025],
    assertions: ['the-blizzard-is-not-in-the-weather-file', 'eighty-four-cents-in-the-dollar'],
    entries: [
      'event/the-tornadoes-of-april-1965.yml',
      'event/allen-county-declared-for-covid-19-2020.yml',
      'event/allen-county-declared-for-hurricane-katrina-2005.yml',
      'event/the-windstorm-of-22-june-2006.yml',
    ],
  },
  {
    slug: 'what-the-county-dug',
    title: 'What the county dug',
    dek: "Allen County's only National Historic Landmark is a canal cut south of Spencerville. Its water is level to 1.8 inches over 7,375 feet, it is 45.8 feet deep rather than 52, and 37 per cent of it is in the next county.",
    section: 'history',
    era: [1845, 2026],
    assertions: [
      'the-water-in-the-cut-does-not-move',
      'fifty-two-feet-and-forty-five-point-eight',
      'five-feet-of-water-closes-the-gap',
      'eighteen-feet-of-the-depth-came-out-of-the-hole',
      'the-water-is-as-wide-as-the-canals-floor',
      'the-landmark-is-thirty-seven-per-cent-in-another-county',
      'the-registers-boundary-is-a-box-over-half-of-it',
      'one-nomination-in-twenty-nine-is-readable',
      'deep-cut-was-a-place-before-it-was-a-landmark',
      'one-canal-three-features-two-spellings',
      'what-carries-the-name-falls-six-feet-to-the-mile',
      'a-field-ditch-in-the-canals-line',
      'the-canal-got-its-name-four-years-after-the-boats',
      'the-first-boat-through-delphos-was-the-marshall',
      'six-point-nine-nine-miles-and-five-more-nobody-draws',
      'how-much-earth-was-moved-is-a-choice-of-datum',
    ],
    entries: [
      'measure/miami-and-erie-canal-deep-cut-2026.yml',
      'measure/miami-and-erie-canal-in-allen-county-2026.yml',
      'site/miami-and-erie-canal.yml',
      'measure/allen-county-national-register.yml',
    ],
  },
  {
    slug: 'the-map-is-of-the-river',
    title: 'The map is of the river',
    dek: "Six per cent of Allen County is in the federal floodplain, and it is not the county's wet ground: hydric soil and flood zone correlate at 0.099. More insured flood damage here comes from rain that had nowhere to go than from a river leaving its channel.",
    section: 'ground',
    era: [1978, 2026],
    assertions: [
      'six-per-cent-of-the-county-is-floodplain',
      'the-five-hundred-year-band-is-a-sixteenth',
      'one-acre-in-seven-has-no-elevation',
      'the-flood-map-is-three-maps',
      'wet-ground-and-flood-zone-are-not-the-same-ground',
      'four-villages-have-no-floodplain-at-all',
      'gomer-is-a-third-floodplain',
      'how-many-people-live-in-the-floodplain',
      'more-rain-than-river',
      'tidal-water-five-hundred-miles-from-the-sea',
      'a-village-of-four-thousand-holds-a-third-of-the-money',
      'june-2015-and-nobody-declared-it',
      'ten-claim-years-and-one-declaration',
      'twenty-seven-buildings-and-one-buyout',
      'half-the-claims-were-rated-outside-the-map',
      'the-ratio-is-about-who-had-to-buy',
    ],
    entries: [
      'measure/allen-county-flood-hazard-2026.yml',
      'measure/allen-county-flood-insurance-1978-2023.yml',
      'measure/allen-county-disaster-declarations-1965-2020.yml',
      'measure/allen-county-hazard-mitigation-2003-2026.yml',
      'place/gomer.yml',
    ],
  },
  {
    slug: 'sent-from-here-held-here',
    title: 'Sent from here, held here',
    dek: "Allen County had 627 of its people in Ohio's prisons in 2019 and 1,513 people in prisons inside it. Its imprisonment rate was below the state's in 1983 and half again above it in 2019, and its jail has been over capacity in twenty-one of twenty-nine years.",
    section: 'government',
    era: [1970, 2023],
    assertions: [
      'sent-from-here-and-held-here',
      'from-two-hundred-and-twenty-four-to-nine-hundred-and-seventy-eight',
      'ohio-stopped-and-this-county-did-not',
      'fewer-sent-and-more-inside',
      'the-criminal-caseload-did-not-move',
      'the-ratio-is-not-a-length-of-stay',
      'eight-times-as-likely',
      'the-jail-rate-more-than-tripled',
      'twenty-one-years-over-capacity',
      'three-quarters-of-the-jail-is-pretrial',
      'this-county-jails-above-the-state',
      'an-eighth-of-the-county-and-a-third-of-the-jail',
      'the-jail-series-is-a-sample',
      'two-rows-that-pass-every-range-check',
      'where-was-the-jail-counted',
      'the-census-lost-a-hundred-and-forty-people',
    ],
    entries: [
      'measure/allen-county-jail-1970-2023.yml',
      'measure/allen-county-in-state-prison-1983-2019.yml',
      'site/allen-county-justice-center.yml',
      'measure/allen-county-court-caseloads-2007-2017.yml',
      'measure/allen-county-group-quarters-2020.yml',
    ],
  },
  {
    slug: 'not-for-sale-and-not-for-rent',
    title: 'Not for sale and not for rent',
    dek: "Allen County had 3,628 empty houses in 2020 and the largest group of them was in no market at all. Over the decade before it the county lost 436 housing units, 1,342 mortgaged owners and, in Lima, its majority of homeowners.",
    section: 'people',
    era: [2010, 2020],
    assertions: [
      'the-largest-kind-of-empty-is-neither',
      'four-hundred-and-two-houses-for-sale',
      'the-vacancy-rates-omit-the-largest-class',
      'every-kind-of-empty-fell-but-the-transactions',
      'the-county-ended-the-decade-with-fewer-houses',
      'it-built-less-than-it-lost',
      'something-was-pulled-down',
      'three-quarters-of-the-loss-is-limas',
      'limas-houses-came-down',
      'the-mortgaged-owners-left',
      'two-in-five-owners-here-owe-nothing',
      'seventy-third-of-eighty-eight-on-owning',
      'lima-stopped-being-a-city-of-owners',
      'owning-not-owing-divides-the-county',
      'twice-as-likely-to-own',
      'the-county-gap-is-wider-than-either-half',
      'black-households-grew-and-black-owners-did-not',
      'the-county-is-ordinary-and-its-interior-is-not',
      'the-total-is-counted-and-the-split-is-not',
      'a-hundred-and-thirty-eight-empty-blocks',
    ],
    entries: [
      'measure/allen-county-vacancy-status-2010-2020.yml',
      'measure/allen-county-tenure-2010-2020.yml',
      'measure/allen-county-occupancy-2020.yml',
      'measure/allen-county-building-permits-1990-2025.yml',
      'measure/allen-county-housing-stock-2023.yml',
      'place/lima.yml',
    ],
  },
  {
    slug: 'the-back-of-the-ballot',
    title: 'The back of the ballot',
    dek: "A hundred and twelve local questions on sixteen election days, and Allen County renewed almost everything and added almost nothing. On one of those ballots a village of three thousand people voted to stop existing.",
    section: 'government',
    era: [2003, 2012],
    assertions: [
      'a-hundred-and-twelve-questions',
      'the-county-renews-and-does-not-add',
      'the-renewal-that-failed-was-not-one',
      'a-replacement-passes-like-a-renewal',
      'new-borrowing-is-the-hardest-ask',
      'beaverdam-refused-three-times',
      'everything-not-about-money-passed',
      'the-busiest-ballot-was-an-odd-year',
      'the-village-surrendered-its-corporate-power',
      'fort-shawnee-refused-to-pay-then-dissolved',
      'two-instruments-put-the-end-in-the-same-year',
      'the-survey-misses-what-a-government-gives-up',
      'thirty-liquor-questions-precinct-by-precinct',
      'an-olive-garden-and-a-red-lobster',
      'carried-by-two-votes',
      'one-precinct-two-answers',
      'no-report-says-what-the-forms-ask',
      'thirteen-questions-filed-elsewhere',
      'a-return-under-a-county-is-not-its-vote',
      'the-elida-return-cannot-be-right',
    ],
    entries: [
      'measure/allen-county-ballot-questions-2003-2012.yml',
      'measure/allen-county-local-option-elections-2003-2012.yml',
      'jurisdiction/village-of-fort-shawnee.yml',
      'question/what-happened-to-the-village-of-fort-shawnee.yml',
      'place/fort-shawnee.yml',
      'measure/allen-county-property-tax-rates-2012-2025.yml',
    ],
  },
  {
    slug: 'a-card-is-not-an-appointment',
    title: 'A card is not an appointment',
    dek: "Allen County's uninsured population fell by more than half in three years, and every one of the people it gained is covered in a county the federal government designates short of primary care, dental care and mental health care. The two facts are answers to different questions.",
    section: 'people',
    era: [1985, 2026],
    assertions: [
      'the-uninsured-fell-by-half-in-three-years',
      'the-children-were-already-covered',
      'the-income-gradient-closed',
      'the-model-was-told-about-the-programme',
      'men-are-less-insured-in-every-year',
      'the-model-and-its-own-survey-part',
      'a-rank-that-moved-twenty-seven-places',
      'an-older-series-that-does-not-join',
      'a-third-of-the-children-are-on-medicaid',
      'one-resident-in-five-holds-public-coverage',
      'forty-one-uninsured-people-over-sixty-five',
      'limas-coverage-is-not-its-poverty-rate',
      'the-uninsured-are-men-in-their-thirties',
      'ninety-seven-of-three-hundred-and-four-trained-abroad',
      'fourth-in-ohio-for-primary-care-residents',
      'below-the-state-on-the-doctors-who-stay',
      'six-psychiatrists-and-no-child-psychiatrist',
      'six-of-eight-obstetricians-are-fifty-five-or-older',
      'more-practitioners-than-physicians',
      'the-designation-is-the-countys-poor',
      'half-a-psychiatrist-for-fifty-thousand-people',
      'the-map-came-down-after-forty-one-years',
      'the-prison-is-designated-on-its-own',
    ],
    entries: [
      'measure/allen-county-health-insurance-2008-2024.yml',
      'measure/allen-county-coverage-types-2023.yml',
      'measure/allen-county-health-workforce-2023.yml',
      'measure/allen-county-shortage-designations-1985-2026.yml',
      'measure/allen-county-transfer-receipts-1969-2024.yml',
      'site/allen-correctional-institution.yml',
    ],
  },
  {
    slug: 'where-the-buildings-are',
    title: 'Where the buildings are',
    dek: "A machine drew a polygon around every roof in Allen County bigger than a two-car garage, and there are 59,433 of them. Nine hundred and six stand on the floodplain, which is a third of the share of the ground that is mapped for flooding.",
    section: 'ground',
    era: [2013, 2026],
    assertions: [
      'fifty-nine-thousand-four-hundred-and-thirty-three-buildings',
      'industry-is-a-fortieth-and-a-seventh',
      'a-structure-is-not-a-housing-unit',
      'thirty-four-cellblocks-filed-as-houses',
      'thirteen-subdivisions-partition-the-roofs',
      'the-largest-roof-in-the-county',
      'no-building-stands-where-the-tank-plant-is-mapped',
      'eight-of-ten-coordinates-hit-no-building',
      'more-buildings-than-addresses',
      'two-hundred-and-fifty-eight-religious-roofs',
      'nine-hundred-and-six-buildings-in-the-floodplain',
      'the-county-built-away-from-its-water',
      'thirty-eight-of-a-hundred-metals-buildings',
      'a-manufactured-home-is-twice-as-likely',
      'thirteen-hundred-and-seventy-six-people',
      'the-crosswalk-leaves-a-hundred-and-eight-blocks',
      'elida-and-delphos-run-the-other-way',
      'five-villages-with-none',
      'one-claim-for-every-nine-buildings-inside',
    ],
    entries: [
      'measure/allen-county-buildings-2019.yml',
      'measure/allen-county-buildings-in-the-floodplain-2026.yml',
      'measure/allen-county-flood-hazard-2026.yml',
      'measure/allen-county-flood-insurance-1978-2023.yml',
      'site/ford-lima-engine-plant.yml',
      'site/lima-army-tank-plant.yml',
    ],
  },
  {
    slug: 'one-job-in-nine',
    title: 'One job in nine',
    dek: "Allen County has forty-five governments and they employ 3,806 people full time. Four of them employ nobody at all, and across eleven years government has never been less than eleven and a half per cent of the county's jobs.",
    section: 'work',
    era: [2014, 2024],
    assertions: [
      'forty-five-governments',
      'three-governments-are-half-the-payroll',
      'the-townships-are-mostly-part-time',
      'four-governments-with-no-employees',
      'eleven-special-districts',
      'what-the-county-government-does',
      'one-jailer-for-every-one-and-a-half-held',
      'seven-governments-did-not-report',
      'one-job-in-nine-is-a-government-job',
      'three-hundred-and-twenty-one-federal-jobs-twice',
      'the-post-office-is-the-federal-government-here',
      'seventy-people-on-the-federal-payroll-at-the-plant',
      'four-hundred-and-fifty-eight-in-the-prisons',
      'a-road-office-a-college-and-a-courthouse',
      'local-government-pay-fell-behind',
      'state-pay-overtook-federal',
      'government-takes-a-ninth-of-the-wages',
      'two-agencies-within-five-per-cent',
      'what-a-business-register-leaves-out',
    ],
    entries: [
      'measure/allen-county-governments-and-their-employees-2022.yml',
      'measure/allen-county-government-employment-2014-2024.yml',
      'measure/allen-county-private-employers-1986-2023.yml',
      'site/lima-army-tank-plant.yml',
      'site/allen-correctional-institution.yml',
      'jurisdiction/allen-county-government.yml',
    ],
  },
  {
    slug: 'where-they-went',
    title: 'Where they went',
    dek: "Nineteen years of tax returns changing address, and Allen County lost people in every one of them. The border with its neighbours comes to a net of eighty-two people; Columbus alone took two thousand.",
    section: 'people',
    era: [2004, 2023],
    assertions: [
      'nineteen-years-nineteen-losses',
      'three-hundred-and-fifty-five-million-left',
      'the-leavers-out-earned-the-arrivers',
      'the-income-gap-is-closing',
      'more-than-half-who-leave-ohio-go-south',
      'two-years-that-are-the-file',
      'the-tax-file-finds-a-smaller-loss',
      'foreign-migration-stops-being-published',
      'forty-five-counties-and-six-hundred-and-ninety-seven-flows',
      'seventeen-thousand-crossings-of-one-county-line',
      'the-border-comes-to-eighty-two',
      'the-loss-is-to-the-cities',
      'columbus-is-a-fifth-of-everything',
      'the-richest-leavers-go-to-delaware-county',
      'two-allen-counties-and-the-ohio-one-loses',
      'five-rural-counties-give-more-than-they-take',
      'where-the-missing-people-went',
    ],
    entries: [
      'measure/allen-county-migration-flows-2004-2023.yml',
      'measure/allen-county-migration-by-county-2004-2023.yml',
      'measure/allen-county-net-migration-2021-2024.yml',
      'measure/allen-county-population-2024.yml',
    ],
  },
  {
    slug: 'the-tests-came-back',
    title: 'The tests came back',
    dek: 'The site recorded 2020 as a year with no scores in it. It has scores, and they are the pandemic \u2014 beside the rule that decides which children may be seen at all.',
    section: 'people',
    era: [2013, 2021],
    assertions: [
      'the-year-this-site-called-empty',
      'the-missing-year-is-the-cancelled-one',
      'eleven-of-the-twelve-districts-fell',
      'limas-mathematics-fell-to-twenty-nine',
      'the-county-pulled-further-from-ohio',
      'exact-by-district-and-banded-by-school',
      'the-four-lowest-schools-are-in-lima',
      'one-school-tests-mathematics-at-seventeen',
      'one-high-school-a-reader-may-read',
      'two-lima-schools-read-higher-in-2020',
      'nine-of-eleven-legible-rows-are-white',
      'only-lima-publishes-its-black-children',
      'the-gap-inside-lima-outlived-the-test',
      'limas-white-children-are-lowest-too',
      'held-to-poor-children-the-spread-holds',
      'in-two-districts-the-poor-are-the-district',
      'disability-is-legible-in-one-district',
      'english-learners-are-never-published',
      'a-subgroup-costs-a-hundred-children',
      'a-school-closed-and-the-count-held',
    ],
    entries: [
      'measure/allen-county-proficiency-by-school-2018-2020.yml',
      'measure/allen-county-proficiency-by-subgroup-2013-2020.yml',
    ],
  },
  {
    slug: 'the-same-ground-after-all',
    title: 'The same ground after all',
    dek: 'Five deeds said the tank plant was bought in 1951 and this site believed them past their edges. The Army\u2019s own report dates the installation to May 1942.',
    section: 'history',
    era: [1942, 1984],
    assertions: [
      'the-plant-was-begun-in-may-1942',
      'the-mission-was-cancelled-before-the-plant-was-finished',
      'a-hundred-thousand-vehicles-passed-through-lima',
      'building-147-is-the-war-still-standing',
      'the-ground-stayed-at-163-acres',
      'the-deed-was-an-expansion-not-a-founding',
      'four-farmhouses-are-numbered-buildings',
      'the-coordinate-sits-on-the-1951-land',
      'the-depot-is-the-plant-under-its-first-name',
      'four-names-for-one-installation',
      'general-dynamics-has-operated-it-since-1982',
      'the-plant-was-nearly-idle-through-vietnam',
      'no-archeologist-has-looked-at-this-ground',
    ],
    entries: [
      'event/the-army-builds-at-lima-1942.yml',
      'site/lima-army-tank-plant.yml',
    ],
  },
  {
    slug: 'thirty-years-past-the-last-history',
    title: 'Thirty years past the last history',
    dek: 'A chamber of commerce booklet of 1952 is the newest narrative account of this county on the shelf, and four things it says are dates nothing else here could give.',
    section: 'history',
    era: [1886, 1951],
    assertions: [
      'limas-mayor-came-back-in-1933',
      'the-commission-form-lasted-eleven-years',
      'the-buses-began-in-1938',
      'two-histories-and-one-fourth-of-july',
      'the-locomotive-works-ended-as-baldwin-lima-hamilton',
    ],
    entries: [
      'event/lima-returns-to-mayor-and-council-1933.yml',
      'event/the-buses-replace-the-streetcars-1938.yml',
    ],
  },
  {
    slug: 'the-smallest-books',
    title: 'The smallest books',
    dek: 'Twelve hundred and sixty state audits of this county\u2019s public bodies. A township audit carries a finding for recovery five times as often as a school audit, and one village asked to be declared in emergency.',
    section: 'government',
    era: [1999, 2026],
    assertions: [
      'twelve-hundred-and-sixty-audits',
      'ninety-seven-per-cent-is-routine',
      'a-quarter-of-the-audited-are-private',
      'forty-five-governments-and-a-hundred-and-eighteen-bodies',
      'the-lists-agree-where-they-overlap',
      'sixty-two-findings-for-recovery',
      'a-township-audit-is-five-times-as-likely',
      'nine-of-twelve-townships-and-seven-of-eight-villages',
      'the-county-and-both-cities-are-in-the-list',
      'ninety-three-thousand-and-three-hundred-thousand',
      'the-court-found-it-in-its-own-books',
      'fort-shawnee-asked-for-the-analysis',
      'three-of-six-conditions-and-fifty-thousand-dollars',
      'more-promised-than-banked',
      'twenty-five-months-to-the-ballot',
      'the-last-day-of-record-is-june-2013',
    ],
    entries: [
      'measure/allen-county-audits-1999-2026.yml',
      'measure/allen-county-findings-for-recovery-1999-2026.yml',
      'event/fort-shawnee-declared-in-fiscal-emergency-2010.yml',
    ],
  },
  {
    slug: 'the-far-side-of-a-field',
    title: 'The far side of a field',
    dek: 'Seven hundred and thirty-five miles of channel, two thirds of it nameless \u2014 and two headwaters 858 metres apart that are seven hundred and fifty miles apart by water.',
    section: 'ground',
    era: [2026, 2026],
    assertions: [
      'seven-hundred-and-thirty-five-miles-of-channel',
      'two-thirds-of-this-county-water-has-no-name',
      'a-name-is-what-runs-all-year',
      'the-county-is-headwater-country',
      'lima-has-the-road-and-not-the-water',
      'where-all-of-it-goes',
      'the-river-is-where-they-meet',
      'three-questions-that-named-one-field',
      'the-auglaize-joins-the-maumee-and-it-is-no-longer-assumed',
      'the-main-stem-is-named-for-a-river-in-indiana',
      'the-little-ottawa-joins-between-the-two-gauges',
      'fort-shawnee-has-more-water-than-lima',
      'the-far-side-of-a-field',
      'the-water-ends-in-the-gulf-of-saint-lawrence',
      'the-ditches-on-the-other-side-have-no-name',
      'one-reach-reaches-nothing',
      'most-of-the-standing-water-is-a-farm-pond',
      'forty-two-acres-of-the-great-black-swamp',
      'a-creek-filed-in-a-county-it-never-touches',
      'the-canal-is-the-county-line',
      'two-files-two-gauges-one-square-mile',
    ],
    entries: [
      'measure/allen-county-stream-network-2026.yml',
      'measure/allen-county-distance-to-the-sea-2026.yml',
      'measure/allen-county-standing-water-2026.yml',
      'natural-feature/blanchard-river.yml',
      'natural-feature/riley-creek.yml',
    ],
  },
  {
    slug: 'a-third-of-the-empty-ones',
    title: 'A third of the empty ones',
    dek: 'Twelve hundred empty houses in this county have no working plumbing \u2014 and the two federal files that say why a house is empty disagree by a factor of three.',
    section: 'people',
    era: [1990, 2023],
    assertions: [
      'a-third-of-the-empty-ones-have-no-plumbing',
      'the-kitchens-say-the-same-thing',
      'in-lima-a-third-and-a-bit-more',
      'the-same-seven-questions-and-two-answers',
      'three-quarters-of-the-empty-ones-are-on-no-market',
      'ordinary-by-one-instrument-and-not-by-the-other',
      'four-houses-in-five-are-one-building',
      'renting-here-means-renting-a-house',
      'there-is-no-condominium-market-here',
      'more-mobile-homes-than-flats-in-large-buildings',
      'where-the-mobile-homes-are',
      'one-mobile-home-in-six-stands-empty',
      'bottled-gas-is-the-map-of-the-gas-main',
      'three-thousand-households-with-no-car',
      'a-renter-here-lacks-a-kitchen',
      'crowded-for-ohio-and-uncrowded-for-america',
      'lima-has-lost-one-housing-unit-in-seven',
      'the-city-was-still-a-city-of-owners-in-1990',
      'almost-nothing-lacked-plumbing-in-1990',
      'five-thousand-six-hundred-households-have-not-moved-since-1989',
      'a-quarter-of-the-1990-answers-were-allocated',
    ],
    entries: [
      'measure/allen-county-housing-facilities-2023.yml',
      'measure/allen-county-housing-structure-2023.yml',
      'measure/allen-county-vacancy-status-2023.yml',
      'measure/allen-county-housing-1990.yml',
    ],
  },
  {
    slug: 'the-same-fourteen-points',
    title: 'The same fourteen points',
    dek: 'Seven presidential elections come out of a ninety-year hole \u2014 and the county turns out to run the same distance ahead of its state, election after election, whatever the election is about.',
    section: 'government',
    era: [1960, 2008],
    assertions: [
      'eighty-four-items-in-six-thousand-six-hundred',
      'thirty-of-thirty-two-sources-are-federal',
      'the-nineteen-sixty-seven-volume-named-its-vendor',
      'nixon-ran-twelve-points-ahead-of-his-state-here',
      'the-state-and-the-county-chose-different-parties',
      'the-volume-prints-no-loser',
      'the-county-was-read-from-the-metropolitan-table',
      'reagan-took-seventy-three-per-cent-of-this-county',
      'perot-took-one-vote-in-six-and-the-republican-still-won-a-majority',
      'one-of-three-hundred-and-seventy-counties',
      'perots-collapse-did-not-go-to-the-democrat',
      'the-turnout-did-not-move-for-sixteen-years',
      'the-same-fourteen-points-every-time',
      'the-county-takes-the-national-swing-and-adds-a-constant',
      'ohio-changed-its-mind-three-times-and-this-county-none',
      'forty-seven-of-eighty-eight-counties-never-moved',
      'the-rank-moves-and-the-gap-does-not',
      'putnam-is-above-it-every-time',
      'three-compilations-agree-on-2000',
      'the-year-with-one-witness-now-has-two-that-disagree',
      'two-of-three-is-a-tally-and-not-a-canvass',
      'twenty-eight-of-forty-two-elections',
      'nineteen-sixty-and-nineteen-eighty-are-three-tenths-apart',
      'harding-is-low-for-this-county',
      'the-window-narrowed-from-nineteen-elections-to-eleven',
    ],
    entries: [
      'measure/allen-county-presidential-vote-1960-1964.yml',
      'measure/allen-county-presidential-vote-1980-1996.yml',
      'measure/allen-county-against-ohio-1980-2008.yml',
    ],
  },
  {
    slug: 'sixty-days-notice',
    title: "Sixty days' notice",
    dek: 'Twenty-three plant closings, 2,624 workers, and the day one Lima forge told the state it was laying people off \u2014 which was the day it laid them off.',
    section: 'work',
    era: [1996, 2017],
    assertions: [
      'twenty-three-closings-in-twenty-two-years',
      'the-villages-outweigh-the-city',
      'ten-of-twenty-two-years-are-empty',
      'two-years-carry-forty-four-per-cent',
      'the-largest-notice-is-not-a-factory-closing',
      'one-plant-appears-twice-under-two-owners',
      'nine-notices-gave-a-number-outside-ohio',
      'the-recession-produced-three-notices-and-all-were-shops',
      'a-threshold-from-underneath',
      'two-thousand-six-hundred-and-twenty-four-against-two-thousand-six-hundred-and-twenty-eight',
      'a-register-that-changes-its-mind-about-a-county',
      'twelve-of-twenty-three-arrived-inside-sixty-days',
      'one-notice-arrived-on-the-day',
      'only-three-notices-clear-ninety-days',
      'five-filings-timed-to-the-statute-and-eighteen-not',
      'the-file-dates-the-state-and-not-the-floor',
      'rapid-response-had-under-sixty-days-half-the-time',
      'thirteen-of-twenty-three-name-a-union',
      'the-car-workers-union-in-a-county-with-no-car-plant',
      'ten-notices-name-nobody-and-half-are-factories',
      'the-union-column-takes-what-the-employer-wrote',
      'nothing-after-2011-names-a-union',
    ],
    entries: [
      'measure/allen-county-layoff-notices-1996-2017.yml',
      'measure/allen-county-layoff-notice-intervals-1996-2017.yml',
      'measure/allen-county-unions-in-layoff-notices-1996-2017.yml',
    ],
  },
]

/** One article by slug. Throws rather than rendering a page with a hole in it. */
export function article(slug: string): Article {
  const found = ARTICLES.find((a) => a.slug === slug)
  if (!found) throw new Error(`no article "${slug}" in the registry`)
  return found
}

/** Every article in one section, earliest era first. */
export function articlesIn(section: SectionKey): Article[] {
  return ARTICLES.filter((a) => a.section === section).toSorted(
    (a, b) => a.era[0] - b.era[0] || a.era[1] - b.era[1],
  )
}

/**
 * Every article that names one corpus node.
 *
 * This is the back-link, and it is the reason `entries` is declared rather than inferred from
 * prose: an entry page can say what has been written about its node without the reading side
 * keeping a second list.
 */
export function articlesAbout(nodeId: string): Article[] {
  return ARTICLES.filter((a) => a.entries.includes(nodeId))
}

/** The era of a piece, as the reading room prints it. */
export function eraLabel(a: Article): string {
  return a.era[0] === a.era[1] ? String(a.era[0]) : `${a.era[0]}–${a.era[1]}`
}

/**
 * Every declared id that does not resolve against the feed.
 *
 * Exported rather than kept in the test so that `read/index.astro` can refuse to build over a
 * broken declaration — the gate runs where the page is rendered, not only where it is tested.
 */
export function unresolvedDeclarations(): string[] {
  const knownAssertions = new Set(feedAssertions.map((a) => a.id))
  const knownNodes = new Set(nodes.map((n) => n.id))
  const bad: string[] = []
  for (const a of ARTICLES) {
    for (const id of a.assertions) {
      if (!knownAssertions.has(id)) bad.push(`${a.slug}: no assertion "${id}" in the feed`)
    }
    for (const id of a.entries) {
      if (!knownNodes.has(id)) bad.push(`${a.slug}: no node "${id}" in the feed`)
    }
  }
  return bad
}
